FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive 


RUN apt-get update && apt-get install vim git build-essential wget git-lfs -y
RUN apt-get install python3-dev python3-pip -y

WORKDIR /tmp

COPY cmake-3.26.3-linux-x86_64.sh /tmp/cmake-install.sh 

# install cmake 3.27
#RUN wget https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.sh \
#      -O /tmp/cmake-install.sh \
RUN chmod u+x /tmp/cmake-install.sh \
      #&& mv /usr/bin/cmake /usr/bin/cmake_old \
      && mkdir /usr/bin/cmake \
      && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
      && rm /tmp/cmake-install.sh

ENV PATH="/usr/bin/cmake/bin:${PATH}"


#RUN pip3 install pre-commit && pip3 install clang-format

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN /opt/conda/bin/conda install -y -c pytorch torchvision==0.15.2


