FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive 


RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
      sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get update && apt-get install vim git build-essential \
      wget git-lfs python3-dev python3-pip  -y

WORKDIR /tmp

COPY cmake-3.30.3-linux-x86_64.sh /tmp/cmake-install.sh 

# install cmake 3.27
#RUN wget https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.sh \
#      -O /tmp/cmake-install.sh \
RUN chmod u+x /tmp/cmake-install.sh \
      #&& mv /usr/bin/cmake /usr/bin/cmake_old \
      && mkdir /usr/bin/cmake \
      && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
      && rm /tmp/cmake-install.sh

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN /opt/conda/bin/conda install -y pytorch torchvision pytorch-cuda=11.8 -c pytorch -c nvidia
RUN pip3 install pre-commit clang-format pybind11

ENV PATH=/usr/bin/cmake/bin:$CONDA_DIR/bin:/opt/conda/lib/python3.10/site-packages/torch/share/cmake/Torch:$PATH
ENV LIB_TORCH=/opt/conda/lib/python3.10/site-packages/torch/lib
ENV PYBIND_PATH=/opt/conda/lib/python3.10/site-packages/pybind11

# 切换到 root 用户
USER root

WORKDIR /root/zhennanc



